let challenge='30 Days Of JavaScript';
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toUpperCase());
console.log(challenge.toLowerCase());
console.log(challenge.substring(0,2);
console.log(challenge.substring(3,21);
console.log(challenge.includes("Script");
console.log(challenge.split());
console.log(challenge.split(' '));
let companies='Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(companies.split(,));
console.log(challenge.replace('JavaScript', 'Python');
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt("J"));
console.log(challenge.IndexOf('a'));
console.log(challenge.lastIndexOf('a'));
let smth='You cannot end a sentence with because because because is a conjunction';
console.log(challenge.lastIndexOf('because'));
console.log(challenge.search('because'));
let spaceStr = ' 30 Days Of JavaScript ';
console.log(spaceStr.trim());
console.log(challenge.startsWith('30 Days'));
console.log(challenge.endsWith('JavaScript'));
console.log(challenge.match(/a/g));
let firstPart = '30 Days of ';
console.log(firstPart.concat('JavaScript'));
console.log(challenge.repeat(2));
